"use strict";

const StudentsHolder = require("./StudentsHolder");
let Students = new StudentsHolder();
let frstStud = {"group" : 55, "number" : 18491, "marks" : [4, 4, 5]};
let scndStud = {"group" : 55, "number" : 18480, "marks" : [2, 3, 5]};
let thrdStud = {"group" : 53, "number" : 18301, "marks" : [2, 3, 3, 4]};
let frthStud = {"group" : 52, "number" : 18405, "marks" : [4, 4, 4]};
let fifthStud = {"group" : 52, "number" : 18333, "marks" : [5, 5, 5]};
let sixthStud = {"group" : 52, "number" : 18133, "marks" : []};
Students.CREATE(frstStud);
Students.CREATE(scndStud);
Students.CREATE(thrdStud);
Students.CREATE(frthStud);
Students.CREATE(fifthStud);
Students.CREATE(sixthStud);
Students.READ(18491);
Students.READ(18480);
Students.READ(18301);
Students.READ(18405);
Students.READ(18333);
console.log("\n");
Students.UPDATE(18491, 56, [5, 2, 4]);
Students.READ(18491);
console.log("\n");
Students.DELETE(18480);
console.log(Students.Students);
console.log("\n");
Students.getAverageMarks(18491);
console.log("\n");
Students.getInfoByGroup(52);
console.log("\n");
Students.getInfoByMaxMarks();
console.log("\n");
Students.getInfoByNoMarks();